version: '3.8'

services:
  frontend:
    build: ./to-do-list
    image: todo-angular-client:latest
    container_name: todo-angular-client
    ports:
      - "80:4000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14-alpine
    container_name: todo-db
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: a_secure_password
      POSTGRES_DB: todolist_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  db-data: